# Home Assistant Configuration
# Mattias@Welponer.net

logger:
  default: warning
  logs:
    homeassistant.components.homematicip_cloud: warning
#    homeassistant.components.device_tracker: info
#    homeassistant.components.automation: debug
#    homeassistant.components.automation_old: debug
#    homeassistant.components.input_boolean: debug
#    homeassistant.components.mqtt: info
    custom_components.robart: warning
    custom_components.moosefs: warning
    custom_components.device_tracker.icloud3: debug
    
# Configuration
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret hass_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  # Customization file
  customize: !include config/customize.yaml
  customize_glob: !include config/customize-ui.yaml
  # Include Packages
  packages: !include_dir_named packages


# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
  themes: !include_dir_merge_named themes

#lovelace:
#  mode: yaml

#hassio:

hacs:
  token: 8fb5e8398cbe1e432fb0f88a988fe2485371e097

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# updater:
  # Optional, allows Home Assistant developers to focus on popular components.
#  include_used_components: true

#custom_updater:
#  show_installable: true
  
# Discover some devices automatically
discovery:

# Zeroconfig
zeroconf:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Set recorder options
recorder:
  purge_interval: 1
  purge_keep_days: 90
#  db_url: mysql://hass:ha55@localhost/hass

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Meter
utility_meter:
  boiler_energy_kwh_hourly:
    source: sensor.boiler_energy_kwh
    cycle: hourly
  boiler_energy_kwh_daily:
    source: sensor.boiler_energy_kwh
    cycle: daily
  boiler_energy_kwh_weekly:
    source: sensor.boiler_energy_kwh
    cycle: weekly
  boiler_energy_kwh_monthly:
    source: sensor.boiler_energy_kwh
    cycle: monthly
  wohnzimmerlicht_energy_kwh_hourly:
    source: sensor.wohnzimmerlicht_energy_kwh
    cycle: hourly
  wohnzimmerlicht_energy_kwh_daily:
    source: sensor.wohnzimmerlicht_energy_kwh
    cycle: daily
  wohnzimmerlicht_energy_kwh_weekly:
    source: sensor.wohnzimmerlicht_energy_kwh
    cycle: weekly
  wohnzimmerlicht_energy_kwh_monthly:
    source: sensor.wohnzimmerlicht_energy_kwh
    cycle: monthly


zeroconf:

# Vacuum
vacuum:
  - platform: robart
    host: 10.0.0.31
  - platform: xiaomi_miio
    host: 10.0.0.51
    token: !secret xiaomi_vacuum


speedtestdotnet:
  scan_interval:
    minutes: 15
  monitored_conditions:
    - ping
    - download
    - upload

media_player:
  - platform: enigma2
    host: 10.0.0.9
    password: regit

remote:
  - platform: harmony
    name: Living
    host: 10.0.0.4

# Weather prediction
weather:
#  - platform: yweather
#    name: Graz
  - platform: darksky
    name: darksky_graz
    api_key: !secret darksky_key
    mode: daily

camera:
  - platform: mjpeg
    mjpeg_url: http://10.0.0.31:2971/camera/stream
    name: WallPanel

# Text to speech
#tts:
#  - platform: google

# Cloud
cloud:

system_health:

mqtt:
  password: !secret mqtt_passwort

history_graph:
  balkon_graph:
    name: Balkon Temperatur
    entities:
      - sensor.balkon_temperature
    hours_to_show: 48
    refresh: 60
  wohnung_graph:
    name: Wohnung Temperatur
    entities:
      - sensor.wohnzimmer_temperature
      - sensor.schlafzimmer_temperature      
      - sensor.kinderzimmer_temperature
      - sensor.kueche_temperature
    hours_to_show: 48
    refresh: 60
  heating_graph:
    name: Wohnung Heating
    entities:
      - sensor.wohnzimmer_heating
      - sensor.schlafzimmer_heating
      - sensor.kinderzimmer_heating
      - sensor.kueche_heating      
    hours_to_show: 48
    refresh: 60
  boiler_graph:
    name: Boiler
    entities:
      - sensor.boiler_energy_kwh_hourly
      - sensor.boiler_energy_kwh_daily
    hours_to_show: 480
    refresh: 60


group: !include config/groups.yaml
automation: !include automations.yaml
#automation old: !include config/automations_old.yaml
script: !include config/scripts.yaml
sensor: !include config/sensors.yaml
binary_sensor: !include config/binary_sensors.yaml
device_tracker: !include config/device_tracker.yaml
zone: !include config/zones.yaml
plant: !include config/plant.yaml


#switch:
#  - platform: rest
#    resource: http://10.0.0.31:10009/set/stop
#    body_on: '{"cmd_id": "2"}'
#    body_off: '{"active": "false"}'
#    is_on_template: '{{ value_json.is_active }}'
#    headers:
#      Content-Type: application/json


input_boolean:
  presence_sw_home:
    name: Home
    initial: off
    icon: mdi:account-multiple
  presence_sw_away:
    name: Away
    initial: off
    icon: mdi:account-off-outline
  presence_sw_guests:
    name: Guest
    initial: off
    icon: mdi:account-multiple

#input_select:
#  home_mode:
#    name: Home Mode
#    icon: mdi:home-account
#    options:
#      - Home
#      - Away
#      - Returning
      