# Home Assistant Configuration
# Mattias@Welponer.net

logger:
  default: warning
  logs:
    homeassistant.components.homematicip_cloud: info
    homeassistant.components.device_tracker: info

# Configuration
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret hass_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  # Customization file
  customize: !include config/customize.yaml
  customize_glob: !include config/customize-ui.yaml

# Enables the frontend
frontend:
#  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
#  themes:
#    happy:
#      primary-color: pink
#    sad:
#      primary-color: blue


lovelace:
  mode: yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

custom_updater:
  show_installable: true
  
# Discover some devices automatically
discovery:

# Zeroconfig
zeroconf:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Set recorder options
recorder:
  purge_interval: 1
  purge_keep_days: 90

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
weather:
  - platform: yweather
    name: Graz
  - platform: darksky
    name: darksky_graz
    api_key: !secret darksky_key
    mode: daily

#camera:
#  - platform: generic
#    still_image_url: https://icons.wxug.com/data/weather-maps/radar/united-states/cadillac-michigan-region-current-radar-animation.gif
#    name: Midwest Radar

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

history_graph:
  balkon_graph:
    name: Balkon Temperatur
    entities:
      - sensor.balkon_temperature
    hours_to_show: 48
    refresh: 60
  wohnung_graph:
    name: Wohnung Temperatur
    entities:
      - sensor.balkon_temperature
      - sensor.wohnzimmer_temperature
      - sensor.schlafzimmer_temperature      
      - sensor.kinderzimmer_temperature
      - sensor.kueche_temperature
    hours_to_show: 48
    refresh: 60
  heating_graph:
    name: Wohnung Heating
    entities:
      - sensor.wohnzimmer_heating
      - sensor.schlafzimmer_heating
      - sensor.kinderzimmer_heating
      - sensor.kueche_heating      
    hours_to_show: 48
    refresh: 60


group: !include config/groups.yaml
automation: !include config/automations.yaml
automation old: !include config/automations_old.yaml
script: !include config/scripts.yaml
sensor: !include config/sensors.yaml
#variable: !include config/variable.yaml
device_tracker: !include config/device_tracker.yaml
zone: !include config/zones.yaml
