- platform: ping
  hosts:
    router: 10.0.0.1
    igray: 10.0.0.10
    iblue: 10.0.0.11
- platform: bluetooth_le_tracker


- platform: tile
  username: !secret tile_user
  password: !secret tile_password
