# Device Tracker

- platform: ping
  hosts:
    egray_vpn: 172.16.25.1
    eblue_vpn: 172.16.25.2
    igray_vpn: 172.16.25.10
    igray_lan: 10.0.0.10
    iwhite_vpn: 172.16.25.12
    iwhite_lan: 10.0.0.12
    worm13_vpn: 172.16.25.100
    
#- platform: bluetooth_le_tracker
#  track_new_devices: True

- platform: tile
  username: !secret tile_user
  password: !secret tile_password

- platform: tile
  username: !secret tile2_user
  password: !secret tile2_password

#- platform: icloud
#  username: !secret icloud_user
#  password: !secret icloud_password  
#  filter_devices: 'iworm'

#- platform: icloud3
#  account_name: mattias_icloud
#  username: !secret icloud_user
#  password: !secret icloud_password
#  track_devices:
#    - iworm > mattias.welponer@me.com, test.png
    
#  filter_devices: 'itiger'
#  include_device_types: 
#    - iphone
#    - ipad
#    - mac
#    - macbook    
#    - mac book
#    - macbook pro
#  inzone_interval: 15
#  stationary_still_time: 360
 
#- platform: icloud3
#  username: !secret icloud2_user
#  password: !secret icloud2_password
#  include_device_types: 
#    - iphone
#    - ipad
#    - mac
#    - macbook    
#  inzone_interval: 15
#  stationary_still_time: 60
  
#- platform: icloud
#  username: !secret icloud2_user
#  password: !secret icloud2_password

