# Device Tracker

- platform: ping
  hosts:
    ping_router: 10.0.0.1
    ping_igray: 10.0.0.10
    ping_iblue: 10.0.0.11

#- platform: bluetooth_le_tracker
#  track_new_devices: True

#- platform: tile
#  username: !secret tile_user
#  password: !secret tile_password

#- platform: tile
#  username: !secret tile2_user
#  password: !secret tile2_password

- platform: icloud3
  username: !secret icloud_user
  password: !secret icloud_password
  filter_devices: 'iworm'

- platform: icloud3
  username: !secret icloud_user
  password: !secret icloud_password
  filter_devices: 'itiger'

- platform: icloud3
  username: !secret icloud_user
  password: !secret icloud_password
  filter_devices: 'ishaf'
  
#- platform: icloud
#  username: !secret icloud2_user
#  password: !secret icloud2_password

