# Home Assiatnt Groups
# Mattias@Welponer.net

# Views
home:
  name: Wohnung
  view: yes
  icon: mdi:home
  entities:
    - group.wetter
    - group.balkon
    - group.balkon_graph
    - group.wohnung
    - group.wohnzimmer
    - group.schlafzimmer
    - group.kinderzimmer
    - group.badezimmer
    - group.kueche
    - group.server_ping
  
   
# Groups
server_ping:
  name: Server Ping
  entities:
    - device_tracker.router
    - device_tracker.igray
    - device_tracker.iblue
    - device_tracker.igreen
    - device_tracker.iwhite

balkon_graph:
  name: Balkon Temperatur
  entities: 
    - history_graph.balkon_temperatur
    - history_graph.wohnung_temperatur

wetter:
  entities:
    - weather.darksky_graz

balkon:
  name: Balkon
  entities:
    - sensor.balkon_temperature
    - sensor.balkon_humidity

wohnung:
  name: Wohnung
  entities:
    - alarm_control_panel.internal
#    - alarm_control_panel.external
    - light.gang_licht
    - binary_sensor.wohnungstuer
    - binary_sensor.gang_smoke
    - binary_sensor.gang_2
    - sensor.gang_illuminance
    - binary_sensor.gang

wohnzimmer:
  name: Wohnzimmer
  entities:
    - light.wohnzimmer_licht
    - climate.wohnzimmer
    - sensor.wohnzimmer_temperature
    - sensor.wohnzimmer_humidity
    - sensor.wohnzimmer_heating
    - sensor.wohnizmmer_illuminance
    - sensor.wohnzimmer_motion

kinderzimmer:
  name: Kinderzimmer
  entities:
    - switch.kinderzimmer_nachtlicht
    - climate.kinderzimmer
    - sensor.kinderzimmer_temperature
    - sensor.kinderzimmer_humidity
    - sensor.kinderzimmer_heating

kueche:
  name: Küche
  entities:
    - climate.kueche
    - sensor.kueche_temperature
    - sensor.kueche_humidity
    - sensor.kueche_heating
    - binary_sensor.water_sensor

badezimmer:
  name: Badezimmer
  entities:
    - climate.badezimmer
    - sensor.badezimmer_temperature
    - sensor.badezimmer_humidity
    - sensor.badezimmer_heating

schlafzimmer:
  name: Schlafzimmer
  entities:
    - climate.schlafzimmer
    - sensor.schlafzimmer_temperature
    - sensor.schlafzimmer_humidity
    - sensor.schlafzimmer_heating

dachboden:
  name: Dachboden
  entities:
    - binary_sensor.dachboden_schachtel

info:
  name: HomeAssistant
  entities:
    - sensor.access_point
    - sensor.current_version

system:
  name: Infos
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping
    - sensor.disk_use_percent_
    - sensor.processor_use
    - sensor.last_boot
