# Home Assiatnt Groups
# Mattias@Welponer.net

# Views
home:
  name: Wohnung
  view: yes
  icon: mdi:home
  entities:
#    - group.wetter
    - group.balkon
    - group.wohnung
    - group.wohnzimmer
    - group.schlafzimmer
    - group.kinderzimmer
    - group.badezimmer
    - group.kueche
    - group.graph

system:
  name: System
  view: yes
  entities:  
    - group.tracker_mattias 
    - group.tracker_martina
    - group.ping_server
       
# Groups
tracker_mattias:
  name: Tracker
  entities:
    - device_tracker.tile_p2af7e9a8ea4e91be17370568f1864032 
    - device_tracker.tile_3149aafa970892c6
    - device_tracker.tile_317419e4e99eb1b4
    - device_tracker.tile_bb812f82d7f4b42e
    - device_tracker.tile_c73649305efbbde1

tracker_martina:
  name: Martina Tracker
  entities:
    - device_tracker.tile_pe94961aac66ff4409fa1b6c1f219ac48
    
ping_server:
  name: Server Ping
  entities:
    - device_tracker.ping_router
    - device_tracker.ping_igray
    - device_tracker.ping_iblue
    - device_tracker.ping_igreen
    - device_tracker.ping_iwhite

graph:
  entities: 
    - history_graph.balkon_temperatur
    - history_graph.wohnung_temperatur

wetter:
  entities:
    - weather.darksky_graz

balkon:
  name: Balkon
  entities:
    - sensor.balkon_temperature
    - sensor.balkon_humidity

wohnung:
  name: Wohnung
  entities:
    - alarm_control_panel.internal
#    - alarm_control_panel.external
    - light.gang_licht
    - binary_sensor.wohnungstuer
    - binary_sensor.gang_smoke
    - binary_sensor.gang_2
    - sensor.gang_illuminance
    - binary_sensor.gang

wohnzimmer:
  name: Wohnzimmer
  entities:
    - light.wohnzimmer_licht
    - climate.wohnzimmer
    - sensor.wohnzimmer_temperature
    - sensor.wohnzimmer_humidity
    - sensor.wohnzimmer_heating
    - sensor.wohnizmmer_illuminance
    - sensor.wohnzimmer_motion

kinderzimmer:
  name: Kinderzimmer
  entities:
    - switch.kinderzimmer_nachtlicht
    - climate.kinderzimmer
    - sensor.kinderzimmer_temperature
    - sensor.kinderzimmer_humidity
    - sensor.kinderzimmer_heating

kueche:
  name: Küche
  entities:
    - climate.kueche
    - sensor.kueche_temperature
    - sensor.kueche_humidity
    - sensor.kueche_heating
    - binary_sensor.water_sensor

badezimmer:
  name: Badezimmer
  entities:
    - climate.badezimmer
    - sensor.badezimmer_temperature
    - sensor.badezimmer_humidity
    - sensor.badezimmer_heating

schlafzimmer:
  name: Schlafzimmer
  entities:
    - climate.schlafzimmer
    - sensor.schlafzimmer_temperature
    - sensor.schlafzimmer_humidity
    - sensor.schlafzimmer_heating

dachboden:
  name: Dachboden
  entities:
    - binary_sensor.dachboden_schachtel

info:
  name: HomeAssistant
  entities:
    - sensor.access_point
    - sensor.current_version

info_system:
  name: Infos
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping
    - sensor.disk_use_percent_
    - sensor.processor_use
    - sensor.last_boot
