# Scripts


restart_hass:
  alias: "Restart Home Assistant"
  sequence:
  - service: homeassistant.restart


vacuum_corridor:
  alias: "Vacuum Gang"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[27700,22500,35000,24800,1]] 

vacuum_living_bed:
  alias: "Vacuum Schlafzimmer+Wohnzimmer"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[24000,25000,28800,32000,1],[28800,25000,35000,32000,1]]     


vacuum_bed:
  alias: "Vacuum Schlafzimmer"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[24000,25000,28800,32000,1]]     

vacuum_living:
  alias: "Vacuum Wohnzimmer"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[28800,25000,35000,32000,1]]            


vacuum_children:
  alias: "Vacuum Kinderzimmer"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: [[24000,18000,27500,25000,1]]  


