# Home Assistant Sensors
# Mattias@Welponer.net

- platform: rest
  resource: http://ip.jsontest.com
  name: "External IP"
  value_template: '{{ value_json.ip }}'

- platform: rest
  resource: http://10.0.0.31:10009/get/status
  name: "Robart Mode"
  value_template: '{{ value_json.mode }}'

- platform: rest
  resource: http://10.0.0.31:10009/get/status
  name: "Robart Charging"
  value_template: '{{ value_json.charging }}'

- platform: rest
  resource: http://10.0.0.31:10009/get/status
  name: "Robart Battery"
  value_template: '{{ value_json.battery_level }}'

- platform: miflora
  mac: 'c4:7c:8d:67:10:cf'
  name: 'Schefflera'
  median: 1

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/battery"
  name: "WallPanel Battery Level"
  unit_of_measurement: "%"
  value_template: '{{ value_json.value }}'
    
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/temperature"
  name: "WallPanel Temperature"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.value }}'

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/light"
  name: "WallPanel Light Level"
  unit_of_measurement: "lx"
  value_template: '{{ value_json.value }}'
    
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/magneticField"
  name: "WallPanel Magnetic Field"
  unit_of_measurement: "uT"
  value_template: '{{ value_json.value }}'

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/pressure"
  name: "WallPanel Pressure"
  unit_of_measurement: "hPa"
  value_template: '{{ value_json.value }}'

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/qrcode"
  name: "WallPanel QR Code"
  value_template: '{{ value_json.value }}'
    
- platform: speedtest
  minute:
    - 2
    - 17
    - 32
    - 47
  monitored_conditions:
    - ping
    - download
    - upload

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
#  - type: network_in
#    arg: eth0
#  - type: network_out
#    arg: eth0
  - type: last_boot


- platform: version
