# Home Assistant Sensors
# Mattias@Welponer.net

#- platform: miflora
#  mac: ''

- platform: speedtest
  minute:
    - 2
    - 17
    - 32
    - 47
  monitored_conditions:
    - ping
    - download
    - upload

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
#  - type: network_in
#    arg: eth0
#  - type: network_out
#    arg: eth0
  - type: last_boot


- platform: version
