# Home Assistant Sensors
# Mattias@Welponer.net

- platform: cert_expiry
  host: welponer.net

- platform: cert_expiry
  host: mxnode.net


- platform: darksky
  api_key: !secret darksky_key
  language: de
  units: si
  forecast:
    - 0
    - 1 
    - 2
    - 3
    - 4
  hourly_forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5 
  monitored_conditions:
    - summary
    - icon
    - temperature
    - cloud_cover
    - temperature_high
    - temperature_low
    - nearest_storm_distance
      
      
- platform: template
  sensors:
    boiler_energy_kwh:
      value_template: '{{ states.switch.boiler.attributes.today_energy_kwh | float }}'
      unit_of_measurement: 'kWh'
    wohnzimmerlicht_energy_kwh:
      value_template: '{{ states.light.wohnzimmer_licht.attributes.energy_counter_kwh | float }}'
      unit_of_measurement: 'kWh'
    ganglicht_energy_kwh:
      value_template: '{{ states.light.gang_licht.attributes.energy_counter_kwh | float }}'
      unit_of_measurement: 'kWh'

- platform: moosefs
  resources:
    - type: chunks_stable
  
- platform: rest
  resource: http://ip.jsontest.com
  name: "External IP"
  value_template: '{{ value_json.ip }}'

- platform: rest
  resource: http://10.0.0.31:10009/get/status
  name: "Robart Mode"
  value_template: '{{ value_json.mode }}'

- platform: rest
  resource: http://10.0.0.31:10009/get/status
  name: "Robart Charging"
  value_template: '{{ value_json.charging }}'

- platform: rest
  resource: http://10.0.0.31:10009/get/status
  name: "Robart Battery"
  value_template: '{{ value_json.battery_level }}'

- platform: miflora
  mac: 'C4:7C:8D:67:10:CF'
  name: 'Benjaminficus'
  median: 1

- platform: miflora
  mac: 'C4:7C:8D:67:0E:DF'
  name: 'Schefflera'
  median: 1

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/battery"
  name: "WallPanel Battery Level"
  unit_of_measurement: "%"
  value_template: '{{ value_json.value }}'
    
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/temperature"
  name: "WallPanel Temperature"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.value }}'

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/light"
  name: "WallPanel Light Level"
  unit_of_measurement: "lx"
  value_template: '{{ value_json.value }}'
    
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/magneticField"
  name: "WallPanel Magnetic Field"
  unit_of_measurement: "uT"
  value_template: '{{ value_json.value }}'

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/pressure"
  name: "WallPanel Pressure"
  unit_of_measurement: "hPa"
  value_template: '{{ value_json.value }}'

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/qrcode"
  name: "WallPanel QR Code"
  value_template: '{{ value_json.value }}'
    
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: disk_use_percent
    arg: /mnt/storage
  - type: disk_free
    arg: /mnt/storage
  - type: disk_use
    arg: /mnt/storage
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: enp0s25
  - type: network_out
    arg: enp0s25
  - type: last_boot
  - type: load_1m
  - type: load_5m
  - type: load_15m 

- platform: version
